language: d
addons:
  apt:
    packages:
      - xvfb
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libgles2-mesa-dev
      - libegl1-mesa-dev
install:
  - export DISPLAY=':99.0'
  - xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
 - dub test -b unittest-cov --compiler=${DC}
after_success:
 - bash <(curl -s https://codecov.io/bash)
